In [35]:
import numpy as np
from sklearn.linear_model import LinearRegression
import plotly.graph_objects as go


Find the equation of the line that comes as near as possible to all the vectors below:

[ 19, 43, 25 ],

[ 9, 21, 15 ],

[ 12, 29, 18 ],

[ 21, 46, 27 ],

[-4, -4, 2 ],

[ 24, 51, 30 ],

[ 5, 14, 11 ]


In [36]:
P = np.array([
    [19, 43, 25],
    [9, 21, 15],
    [12, 29, 18],
    [21, 46, 27],
    [-4, -4, 2],
    [24, 51, 30],
    [5, 14, 11]
])

x, y, z = zip(*P)

X = np.array(list(zip(x, y)))
Y = z
X, list(Y)


(array([[19, 43],
        [ 9, 21],
        [12, 29],
        [21, 46],
        [-4, -4],
        [24, 51],
        [ 5, 14]]),
 [25, 15, 18, 27, 2, 30, 11])

In [37]:
fig = go.Figure(data=[go.Scatter3d(
    x=x,
    y=y,
    z=z,
    mode='markers',
    marker=dict(
        color=z,                # set color to an array/list of desired values
        colorscale='Viridis',   # choose a colorscale
        opacity=0.8
    )
)])

fig.show()


In [38]:
"""
V0 = [0, y0, z0]
s = [1, sy, sz]

u = V0 + t * s

{ t1 = x1
{ sy*t1 + y0 = y1
{ sz*t1 + z0 = z1

{ sy*x1 + y0 = y1
{ sz*x1 + z0 = z1
    
A = | x1 0 1 0 | * | sy sz y0 z0 | = | y1 z1 |
    | 0 x1 0 1 |
"""

A = np.array([
    [19, 0, 1, 0],
    [0, 19, 0, 1],
    [9, 0, 1, 0],
    [0, 9, 0, 1],
    [12, 0, 1, 0],
    [0, 12, 0, 1],
    [21, 0, 1, 0],
    [0, 21, 0, 1],
    [-4, 0, 1, 0],
    [0, -4, 0, 1],
    [24, 0, 1, 0],
    [0, 24, 0, 1],
    [5, 0, 1, 0],
    [0, 5, 0, 1]
])
B = np.array([
    43, 25, 21, 15, 29, 18, 46, 27, -4, 2, 51, 30, 14, 11
])

sy, sz, y0, z0 = np.linalg.pinv(A).dot(B).round()
sy, sz, y0, z0


(2.0, 1.0, 4.0, 6.0)

In [39]:
s = np.array([1, sy, sz])
v0 = np.array([0, y0, z0])
s, v0


(array([1., 2., 1.]), array([0., 4., 6.]))

In [40]:
def project(v, v0, s):
    return s * (v - v0).dot(s) / s.dot(s) + v0


for v in P:
    print(v, project(v, v0, s))


[19 43 25] [19.33333333 42.66666667 25.33333333]
[ 9 21 15] [ 8.66666667 21.33333333 14.66666667]
[12 29 18] [12.33333333 28.66666667 18.33333333]
[21 46 27] [21. 46. 27.]
[-4 -4  2] [-4. -4.  2.]
[24 51 30] [23.66666667 51.33333333 29.66666667]
[ 5 14 11] [ 5. 14. 11.]
