In [18]:
import numpy as np
from sklearn.linear_model import LinearRegression


There are five 4D vectors:

[1, 3, 5, 7],

[-1, 2, -3, 0],

[0, 1, 1,-1],

[0, 2, 1, 1],

[-2, 4, -5, 4]

Find a 2D plane, so all these vectors almost belong to it.


In [19]:
P = np.array([
    [1, 3, 5, 7],
    [-1, 2, -3, 0],
    [0, 1, 1, -1],
    [0, 2, 1, 1],
    [-2, 4, -5, 4]
])

x, y, z, k = zip(*P)
x, y, z, k


((1, -1, 0, 0, -2), (3, 2, 1, 2, 4), (5, -3, 1, 1, -5), (7, 0, -1, 1, 4))

In [20]:
"""
b1 = [0,1,c,d]
b2 = [1,0,e,f]
v0 = [0,0,g,h]

v = v0 + b1 * t1 + b2 * t2

|0|*t1 + |1|*t2 + |0| = |x1|
|1|*t1 + |0|*t2 + |0| = |y1|
|c|*t1 + |e|*t2 + |g| = |z1|
|d|*t1 + |f|*t2 + |h| = |k1|

{ t1 = x1
{ t2 = y1

{ c*y1 + e*x1 + g = z1
{ d*y1 + f*x1 + h = k1

|c|   |y1,0,x1,0,1,0|
|d|   |0,y1,0,x1,0,1|
|e|   | ... |            |z1 |
|f| * | ... |          = |w1 |
|g|   | ... |            |...|
|h|   | ... |

"""

for x, y, z, k in P:
    A = np.array([
        [y, 0, x, 0],
        [0, y, 0, x],
    ])
    b = np.array([z, k])

    print(np.linalg.pinv(A).dot(b))


[1.5 2.1 0.5 0.7]
[-1.2  0.   0.6  0. ]
[ 1. -1.  0.  0.]
[0.5 0.5 0.  0. ]
[-1.   0.8  0.5 -0.4]


In [ ]:
def get_A_b(v):
    m = []
    b = []
    for x, y, z, k in v:
        m.append(np.array([[y, 0, x, 0, 1, 0], [0, y, 0, x, 0, 1]]))
        b.append(np.array([z, k]))
    return np.vstack(m), np.hstack(b)
