In [540]:
import numpy as np
import matplotlib.pyplot as plt

The camera is placed at 2.5 meters above the floor and
directed exactly to the room’s corner which is the origin
of the global reference frame as shown in the picture.

The roll angle of the camera is 0.
Find the extrinsic camera matrix


In [541]:
camera_origin = np.array([5, 5, 2.5])

In [542]:
def angle(v1, v2):
    return np.arccos(np.dot(v1, v2) / (np.linalg.norm(v1) * np.linalg.norm(v2)))


a1 = np.deg2rad(90 + 45)
a2 = np.deg2rad(-90) - angle(camera_origin, np.array([5, 5, 0]))
a3 = 0

In [543]:
c1 = np.cos(a1)
c2 = np.cos(a2)
c3 = np.cos(a3)
s1 = np.sin(a1)
s2 = np.sin(a2)
s3 = np.sin(a3)

ZXZ = np.array([
    [c1*c3 - c2*s1*s3, -c1*s3 - c2*c3*s1, s1*s2],
    [c3*s1 + c1*c2*s3, c1*c2*c3 - s1*s3, -c1*s2],
    [s2*s3, c3*s2, c2]
])

E = np.column_stack((ZXZ.T, -ZXZ.T.dot(camera_origin)))
E.round(2)

array([[-0.71,  0.71, -0.  , -0.  ],
       [ 0.24,  0.24, -0.94, -0.  ],
       [-0.67, -0.67, -0.33,  7.5 ]])

In [544]:
E.dot(np.array([0, 0, 0, 1])).round(2)

array([-0. , -0. ,  7.5])

In [545]:
E.dot(np.array([0, 1, 0, 1])).round(2)

array([0.71, 0.24, 6.83])

In [546]:
R1 = np.array([
    [np.cos(a1), -np.sin(a1), 0],
    [np.sin(a1), np.cos(a1), 0],
    [0, 0, 1]
])
R2 = np.array([
    [1, 0, 0],
    [0, np.cos(a2), -np.sin(a2)],
    [0, np.sin(a2), np.cos(a2)]
])
R3 = np.array([
    [np.cos(a3), -np.sin(a3), 0],
    [np.sin(a3), np.cos(a3), 0],
    [0, 0, 1]
])

R = R1.dot(R2.dot(R3))

E = np.column_stack((R.T, -R.T.dot(camera_origin)))
E.round(2)

array([[-0.71,  0.71,  0.  , -0.  ],
       [ 0.24,  0.24, -0.94, -0.  ],
       [-0.67, -0.67, -0.33,  7.5 ]])

In [547]:
print(
    E.dot(np.array([0, 0, 0, 1])).round(2),
    E.dot(np.array([1, 0, 0, 1])).round(2),
    E.dot(np.array([0, 1, 0, 1])).round(2),
    E.dot(np.array([0, 0, 1, 1])).round(2),
)

[-0.  -0.   7.5] [-0.71  0.24  6.83] [0.71 0.24 6.83] [-0.   -0.94  7.17]
