In [7]:
import numpy as np


Find the affine transformation (affine matrix) if we know that it transforms vectors as shown bellow:

a = (1, 2) —> a’ = (9, 15)

b = (2, 1) —> b’ = (8, 14)

c = (3, 3) —> c’ = (16, 28)

In [8]:
a = np.array([1, 2])
b = np.array([2, 1])
c = np.array([3, 3])
a1 = np.array([9, 15])
b1 = np.array([8, 14])
c1 = np.array([16, 28])

ax, ay = a
bx, by = b
cx, cy = c
a1x, a1y = a1
b1x, b1y = b1
c1x, c1y = c1

```
m1 * ax + m2 * ay + tx = a1x
m3 * ax + m4 * ay + ty = a1y
m1 * bx + m2 * by + tx = b1x
m3 * bx + m4 * by + ty = b1y
m1 * cx + m2 * cy + tx = c1x
m3 * cx + m4 * cy + ty = c1y

m1 + 2m2 + tx = 9
m1 + 2m4 + ty = 15
2m1 + m2 + tx = 8
2m3 + m4 + ty = 14
3m1 + 3m2 + tx = 16
3m3 + 3m4 + ty = 28

A = [
    [0, 0, 0, 1, 2, 1], 
    [1, 2, 1, 0, 0, 0], 
    [0, 0, 0, 2, 1, 1],
    [2, 1, 1, 0, 0, 0],
    [0, 0, 0, 3, 3, 1],
    [3, 3, 1, 0, 0, 0]
]

B = [[
    9,
    15,
    8,
    14,
    16,
    28
]]

M = A^-1 * B = [
    [2 3 1]
    [4 5 1]
    [0 0 1]
]
```

In [9]:
A = np.array([
    [0, 0, 0, ax, ay, 1],
    [ax, ay, 1, 0, 0, 0],
    [0, 0, 0, bx, by, 1],
    [bx, by, 1, 0, 0, 0],
    [0, 0, 0, cx, cy, 1],
    [cx, cy, 1, 0, 0, 0]
])
A1 = np.linalg.inv(A)

B = np.array([[a1x, a1y, b1x, b1y, c1x, c1y]]).T

m3, m4, tx, m1, m2, ty = A1.dot(B)

M = np.array([
    [m1[0], m2[0], tx[0]],
    [m3[0], m4[0], ty[0]],
    # [0, 0, 1],
])

a2 = M.dot(np.concatenate([a, [1]]))
b2 = M.dot(np.concatenate([b, [1]]))
c2 = M.dot(np.concatenate([c, [1]]))

print(a2)
print(b2)
print(c2)
M

[ 9. 15.]
[ 8. 14.]
[16. 28.]


array([[2., 3., 1.],
       [4., 5., 1.]])