In [670]:
import numpy as np
import matplotlib.pyplot as plt
import plotly.graph_objects as go
from sklearn.decomposition import PCA


Find the equation of the line that comes as near as possible to all the vectors below.

Hint: use PCA to find the first principal vector which direction must be along the line.

[19, 43, 25 ], [ 9, 21, 15 ], [ 12, 29, 18 ], [ 21, 46, 27 ], [-4, -4, 2 ],[ 24, 51, 30 ], [ 5, 14, 11 ]


In [671]:
A = np.array([
    [19, 43, 25],
    [9, 21, 15],
    [12, 29, 18],
    [21, 46, 27],
    [-4, -4, 2],
    [24, 51, 30],
    [5, 14, 11]
])
A


array([[19, 43, 25],
       [ 9, 21, 15],
       [12, 29, 18],
       [21, 46, 27],
       [-4, -4,  2],
       [24, 51, 30],
       [ 5, 14, 11]])

In [672]:
center = np.mean(A, axis=0)
Ac = A - center
Ac


array([[  6.71428571,  14.42857143,   6.71428571],
       [ -3.28571429,  -7.57142857,  -3.28571429],
       [ -0.28571429,   0.42857143,  -0.28571429],
       [  8.71428571,  17.42857143,   8.71428571],
       [-16.28571429, -32.57142857, -16.28571429],
       [ 11.71428571,  22.42857143,  11.71428571],
       [ -7.28571429, -14.57142857,  -7.28571429]])

In [673]:
U, S, V = np.linalg.svd(Ac)


In [674]:
S.round(2)


array([59.32,  1.15,  0.  ])

In [675]:
V = V.round(2)
V


array([[-0.41, -0.82, -0.41],
       [ 0.58, -0.58,  0.58],
       [ 0.71,  0.  , -0.71]])

In [676]:
Anew = A.dot(V.T).round(2)
Anew

array([[-53.3 ,   0.58,  -4.26],
       [-27.06,   1.74,  -4.26],
       [-36.08,   0.58,  -4.26],
       [-57.4 ,   1.16,  -4.26],
       [  4.1 ,   1.16,  -4.26],
       [-63.96,   1.74,  -4.26],
       [-18.04,   1.16,  -4.26]])

In [677]:
v1 = V[:1]
s = v1 / np.linalg.norm(v1)
s


array([[-0.40824829, -0.81649658, -0.40824829]])

In [678]:
# V = V1 + t(V2 - V1)
# center = V1
# s = V2 - V1
# V = center + t * s
# Tscalars = [t1]

A = np.vstack((center, s)).T
b = Anew[:, :3].T
Tscalars = np.linalg.pinv(A).dot(b)
L = A.dot(Tscalars).round(2).T
Tscalars[:1].T

array([[ 5.60482759],
       [ 2.39793103],
       [ 3.52655172],
       [ 6.07965517],
       [-1.34275862],
       [ 6.85137931],
       [ 1.32931034]])

In [679]:
x, y, z = zip(*Ac)
x1, y1, z1 = zip(*Anew)
x2, y2, z2 = zip(*L)
xc, yc, zc = zip(center)
fig = go.Figure(data=[
    go.Scatter3d(x=x, y=y, z=z, name="Ac"),
    go.Scatter3d(x=x1, y=y1, z=z1, name="Anew"),
    go.Scatter3d(x=x2, y=y2, z=z2, name="Line"),
    go.Scatter3d(x=xc, y=yc, z=zc, name="Center"),
])
fig.show()