In [25]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression


There are twenty 6-dimensional vectors given in “dimreduction.cvs” file.

Reduce the number of dimensions of the dataset.

How many columns do you need? Find a new reference frame (a new basis and a
new origin) of the reduced dataset.


In [26]:
D = pd.read_csv('./3.csv', header=None)
A = D.to_numpy()
D


0   1   2   3   4   5
0   41   4  54  26  17  39
1   22  26  26   4  30   7
2   48   5  64  25  22  41
3   38  12  50  18  24  29
4   54   1  73  29  21  48
5   32  11  40  19  19  28
6   30  27  37   3  34  10
7   53   9  73  21  28  41
8   43   5  57  25  19  39
9   54   2  73  28  22  47
10  25  16  29  14  21  19
11  36  14  47  16  25  26
12  42  18  56  12  31  26
13  39  12  51  18  24  30
14  41  22  54   8  34  21
15  55   5  74  25  25  45
16  45   7  59  23  22  38
17  37  21  47   9  32  20
18  53   1  72  29  20  48
19  27  24  33   6  30  12

In [27]:
center = np.mean(A, axis=0)
Ac = A - center

In [28]:
U, S, V = np.linalg.svd(Ac)


In [29]:
U.round(2)[:5, :]


array([[-0.1 ,  0.34, -0.14,  0.18, -0.15,  0.32,  0.3 ,  0.06, -0.23,
        -0.1 ,  0.18,  0.15,  0.11,  0.01,  0.04, -0.05, -0.04,  0.46,
        -0.31,  0.4 ],
       [ 0.42,  0.04,  0.32,  0.21,  0.21,  0.46,  0.12,  0.17,  0.12,
         0.12, -0.1 , -0.05,  0.23,  0.06,  0.4 ,  0.22,  0.11,  0.03,
         0.23, -0.07],
       [-0.18,  0.05,  0.27, -0.09,  0.  , -0.16, -0.11,  0.6 , -0.09,
        -0.22, -0.34,  0.1 ,  0.34,  0.01,  0.08, -0.24, -0.3 , -0.12,
        -0.06,  0.12],
       [ 0.04,  0.08,  0.28,  0.3 ,  0.01, -0.37, -0.02,  0.01, -0.33,
        -0.1 , -0.15, -0.51, -0.06, -0.21, -0.03,  0.28,  0.1 ,  0.28,
        -0.21, -0.17],
       [-0.31,  0.01,  0.27, -0.08, -0.05, -0.11,  0.34, -0.39,  0.13,
        -0.33,  0.2 , -0.2 ,  0.1 ,  0.04,  0.5 , -0.18, -0.01, -0.19,
         0.  , -0.  ]])

In [30]:
S.round()


array([108.,  36.,   2.,   1.,   1.,   0.])

In [31]:
V.round(2)


array([[-0.4 ,  0.32, -0.59, -0.32,  0.12, -0.52],
       [-0.33, -0.39, -0.5 ,  0.39, -0.54,  0.22],
       [ 0.06, -0.49,  0.  ,  0.49,  0.46, -0.55],
       [-0.7 , -0.01,  0.62,  0.01, -0.24, -0.25],
       [-0.49, -0.04, -0.08,  0.04,  0.66,  0.57],
       [ 0.  , -0.71, -0.  , -0.71, -0.  ,  0.  ]])

In [32]:
S = np.diag(S).round(2)
Sz = np.zeros((14, 6))
S = np.concatenate((S, Sz), axis=0)
S


array([[107.72,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ],
       [  0.  ,  35.61,   0.  ,   0.  ,   0.  ,   0.  ],
       [  0.  ,   0.  ,   1.5 ,   0.  ,   0.  ,   0.  ],
       [  0.  ,   0.  ,   0.  ,   1.46,   0.  ,   0.  ],
       [  0.  ,   0.  ,   0.  ,   0.  ,   0.87,   0.  ],
       [  0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ],
       [  0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ],
       [  0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ],
       [  0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ],
       [  0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ],
       [  0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ],
       [  0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ],
       [  0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ],
       [  0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ],
       [  0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ],
       [  0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ],
       [  0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ],
       [  0.  ,   0.  ,   0.  ,

In [33]:
Ac.dot(V.T).round()


array([[-11.,  12.,  -0.,   0.,  -0.,  -0.],
       [ 46.,   1.,   0.,   0.,   0.,  -0.],
       [-19.,   2.,   0.,  -0.,   0.,   0.],
       [  4.,   3.,   0.,   0.,   0.,  -0.],
       [-33.,   0.,   0.,  -0.,  -0.,   0.],
       [ 11.,  13.,  -1.,  -0.,  -0.,  -0.],
       [ 35.,  -9.,   0.,  -0.,  -0.,  -0.],
       [-23., -11.,  -1.,   0.,   1.,   0.],
       [-13.,   8.,  -0.,   0.,  -0.,  -0.],
       [-32.,  -1.,   0.,  -0.,  -0.,   0.],
       [ 29.,  14.,  -0.,  -0.,   0.,  -0.],
       [  9.,   2.,   0.,   0.,   0.,  -0.],
       [  5., -11.,  -0.,   0.,   0.,   0.],
       [  2.,   2.,  -0.,   0.,   0.,  -0.],
       [ 12., -15.,  -0.,   0.,  -0.,   0.],
       [-30.,  -6.,  -0.,  -1.,   0.,   0.],
       [-12.,   3.,  -0.,  -0.,   0.,   0.],
       [ 17.,  -9.,   0.,  -1.,   0.,  -0.],
       [-33.,   2.,  -0.,   0.,  -0.,   0.],
       [ 36.,  -1.,  -0.,  -0.,   0.,  -0.]])

In [34]:
b1, b2 = V.T[:2, :2].round(2)
b1, b2


(array([-0.4 , -0.33]), array([ 0.32, -0.39]))

In [35]:
US = U.dot(S).round()
US, US.T


(array([[-11.,  12.,  -0.,   0.,  -0.,   0.],
        [ 46.,   1.,   0.,   0.,   0.,   0.],
        [-19.,   2.,   0.,  -0.,   0.,   0.],
        [  4.,   3.,   0.,   0.,   0.,   0.],
        [-33.,   0.,   0.,  -0.,  -0.,   0.],
        [ 11.,  13.,  -1.,  -0.,  -0.,   0.],
        [ 35.,  -9.,   0.,  -0.,  -0.,   0.],
        [-23., -11.,  -1.,   0.,   1.,   0.],
        [-13.,   8.,  -0.,   0.,  -0.,   0.],
        [-32.,  -1.,   0.,  -0.,  -0.,   0.],
        [ 29.,  14.,  -0.,  -0.,   0.,   0.],
        [  9.,   2.,   0.,   0.,   0.,   0.],
        [  5., -11.,  -0.,   0.,   0.,   0.],
        [  2.,   2.,  -0.,   0.,   0.,   0.],
        [ 12., -15.,  -0.,   0.,  -0.,   0.],
        [-30.,  -6.,  -0.,  -1.,   0.,   0.],
        [-12.,   3.,  -0.,  -0.,   0.,   0.],
        [ 17.,  -9.,   0.,  -1.,   0.,   0.],
        [-33.,   2.,  -0.,   0.,  -0.,   0.],
        [ 36.,  -1.,  -0.,  -0.,   0.,   0.]]),
 array([[-11.,  46., -19.,   4., -33.,  11.,  35., -23., -13., -32.,  29.,
   

In [36]:
V.T.round()


array([[-0., -0.,  0., -1., -0.,  0.],
       [ 0., -0., -0., -0., -0., -1.],
       [-1., -1.,  0.,  1., -0., -0.],
       [-0.,  0.,  0.,  0.,  0., -1.],
       [ 0., -1.,  0., -0.,  1., -0.],
       [-1.,  0., -1., -0.,  1.,  0.]])