In [60]:
import numpy as np


For the given matrices: 

A(2 x 3), B(2 x 2), C(3 x 3), D(3 x 4) 

of (n rows x m columns) find which expression are legit:

(a) AB (b) BA (с) AC (d) ACD (e) DtAt (f) C Dt (g) (AtB)t D

a. A * B - (2x3)(2x2) `n` 3 and 2 dimentions are not equal, so we can`t multiply matrix

b. B * A - (2x2)(2x3) it is legitime, inner `n` are same, new matrix will be (2x3)

c. A * C - (2x3)(3x3) it is legitime, inner `n` are same, new matrix will be (2x3)

d. A * C * D - it is legitime, AC -> (2x3) and (AC)D => (2x3)(3x4). new matrix will be (2x4)

e. Dt * At - it is legitime, after transpose D(3x4) => Dt(4x3) and A(2x3) => At(3x2), so new matrix will be (4x2)

f. C * Dt - C(3x3) * Dt(4x3), C columns count is not equal D rows count, it is not legitim

g. (At * B)t * D - it is legitime, At(3x2), B(2x2), (At*B)t(2x3), D(3x4), new matrix will be (2x4)

In [61]:
A = np.array([
    [1,2,3],
    [4,7,5],
])
B = np.array([
    [1,2],
    [4,7],
])
C = np.array([
    [1,2,3],
    [4,7,1],
    [3,5,7],
])
D = np.array([
    [1,2,4,1],
    [4,7,6,3],
    [3,5,7,1],
])

A,B,C,D

(array([[1, 2, 3],
        [4, 7, 5]]),
 array([[1, 2],
        [4, 7]]),
 array([[1, 2, 3],
        [4, 7, 1],
        [3, 5, 7]]),
 array([[1, 2, 4, 1],
        [4, 7, 6, 3],
        [3, 5, 7, 1]]))