In [17]:
import numpy as np
import scipy.linalg
import sympy

Solve the system of equations below:

x + y = 1 − z

x − 5 = 2z

2x + 1 = y + 2z

2y + z = 7

In [18]:
# x + y = 1 − z
# x − 5 = 2z
# 2x + 1 = y + 2z
# 2y + z = 7

# 1x + 1y + 1z = 1
# 1x + 0y − 2z = 5 
# 2x - 1y - 2z = -1 
# 0x + 2y + 1z = 7

# [-1,5,-3]

# a = [x,y,z,k]
b = np.array([1,5,-1,7])
AA = [
    [1,1,1],
    [1,0,-2],
    [2,1,-2],
    [0,2,1]
]
A = [
    [1,1,1,b[0]],
    [1,0,-2,b[1]],
    [2,1,-2,b[2]],
    [0,2,1,b[3]]
]
# A * a = b
# a = Ai * b

rank = np.linalg.matrix_rank(AA)
print(rank, np.linalg.inv(A))

m,p = sympy.Matrix(AA).rref()
a = np.array([-1,5,-3])
print(a, m, p)
# print(np.array(m).dot(b))
"""
[
    [1, 0, 0, 0],
    [0, 1, 0, 0],
    [0, 0, 1, 0],
    [0, 0, 0, 1]
]
"""
np.array(AA).dot(a)


3 [[ 0.86  0.34 -0.1  -0.38]
 [-0.5  -0.5   0.5   0.5 ]
 [ 0.58  0.02 -0.3  -0.14]
 [ 0.06  0.14 -0.1   0.02]]
[-1  5 -3] Matrix([[1, 0, 0], [0, 1, 0], [0, 0, 1], [0, 0, 0]]) (0, 1, 2)


array([1, 5, 9, 7])